# This file was generated by GoReleaser. DO NOT EDIT.
cask "terrastate" do
  version "2.3.0"

  on_macos do
    on_arm do
      sha256 "f9dd07a7705e616032e7b54096889784834c289a2c6ab71b2339ddf05f3a49b9"
      url "https://github.com/janritter/terrastate/releases/download/#{version}/terrastate_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "ba34dfb4b2b9e9a55df13c0f4bc08ca210ad2ffc9d18772c498048789c55dadd"
      url "https://github.com/janritter/terrastate/releases/download/#{version}/terrastate_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "cbd94a54f8079a7ded4c71d12aeab934907eb6c4261c7384d03354718e39624e"
      url "https://github.com/janritter/terrastate/releases/download/#{version}/terrastate_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "54ca9c8ea0b8de7e51e826567efe445fc912db0fd10ba2ba85fcad444f5b7e51"
      url "https://github.com/janritter/terrastate/releases/download/#{version}/terrastate_linux_amd64.tar.gz"
    end
  end

  name "terrastate"
  desc "Tool to manage multiple states in Terraform - Allows Multi account setups"
  homepage "https://github.com/janritter/terrastate"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "terrastate"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/terrastate"]
    end
  end

  # No zap stanza required
end
