# This file was generated by GoReleaser. DO NOT EDIT.
cask "terrastate" do
  name "terrastate"
  desc "Tool to manage multiple states in Terraform - Allows Multi account setups"
  homepage "https://github.com/janritter/terrastate"
  version "2.2.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "terrastate"

  on_macos do
    on_intel do
      url "https://github.com/janritter/terrastate/releases/download/#{version}/terrastate_darwin_amd64.tar.gz"
      sha256 "0f1c90c14351882872592121f66dbd0c93d4907df2eaee8419b95e5c779cd02f"
    end
    on_arm do
      url "https://github.com/janritter/terrastate/releases/download/#{version}/terrastate_darwin_arm64.tar.gz"
      sha256 "f6a618b6a35df86a954663a7c0bc3535954649badbd5a732a62c89e2338ca70b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/janritter/terrastate/releases/download/#{version}/terrastate_linux_amd64.tar.gz"
      sha256 "233b6c266667cecd914fcf750e23dea288ace5177ab67f009df508ec2da47387"
    end
    on_arm do
      url "https://github.com/janritter/terrastate/releases/download/#{version}/terrastate_linux_arm64.tar.gz"
      sha256 "ff5264f05249f4741e9e74fdfb1cd24d0f350b712124c2ce8d1510617d586cf6"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/terrastate"]
    end
  end

  # No zap stanza required
end
