# This file was generated by GoReleaser. DO NOT EDIT.
cask "terrastate" do
  version "2.2.2"

  on_macos do
    on_intel do
      sha256 "f7fda2a77f5dab00bd849668b405427414220eaee02074cd564c3fd1e151dd74"
      url "https://github.com/janritter/terrastate/releases/download/#{version}/terrastate_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "e20dd4e577476896e1369beec4fe879568a7bf6c1ba78ab3d0b04b6e4846ec6d"
      url "https://github.com/janritter/terrastate/releases/download/#{version}/terrastate_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "01ce87e7e015400bdfa391327b51c63d85c57975d0a64dad3d053740eca2f988"
      url "https://github.com/janritter/terrastate/releases/download/#{version}/terrastate_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "0d7fd42b3a6b42dfb4c21fedc995f595900aec6bfa8474fdb32d5f680e9914fd"
      url "https://github.com/janritter/terrastate/releases/download/#{version}/terrastate_linux_arm64.tar.gz"
    end
  end

  name "terrastate"
  desc "Tool to manage multiple states in Terraform - Allows Multi account setups"
  homepage "https://github.com/janritter/terrastate"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "terrastate"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/terrastate"]
    end
  end

  # No zap stanza required

end
